---
title: "Openscapes Newsletter #8: Fall 2023"
author:
  - name: Julie Lowndes
    orcid: 0000-0003-1682-3872
  - name: Stefanie Butland
    orcid: 0000-0002-5427-8951  
date: 2023-10-05
draft: true
citation: 
  url: https://openscapes.org/blog/2023-09-27
categories: [how-we-work, blog]
#image: 
---

*Welcome to Openscapes’ eighth newsletter! If you’re interested in seeing these infrequent updates in your inbox, please [sign up here](https://docs.google.com/forms/d/e/1FAIpQLSdgVXRp3V-w94GPWkR31RUfyBl37EphdQSlCOcnyeNlf8OLWw/viewform) (linked from our get involved page). And! If you have signed up but did not see this in your inbox, please check your spam folder!*

Happy Fall; it feels like it happened all of a sudden in Santa Barbara, California and Kamloops British Columbia. Ileana and Erin are both working on their quals; Eli has been in India teaching xx. This is a short update, first on events coming up this Fall and then sharing 

## Upcoming Fall events

A few events coming up this fall we hope to see you at:

- Oct 5: 
- Oct 17 
- AGU: 
- NASA Openscapes: updating the [mentors page]() with calendar and activities; grateful to be partnering and coworking with Yuvi Panda, Carl Boettiger, and Coiled.io, and others on cloud infrastructure
- onboarding 3 groups: NASA, NOAA, Hutch

## NASA Openscapes Cloud Support

- R Cloud hackdays 
https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/discussions/247#discussioncomment-7138029

- Coiled 

## Other Spring and Summer Review

One of the themes that keeps coming up, particularly in this 2023 Year of Open Science is "showing up at other people's parties"; and we've been grateful to (re)connect with colleagues virtually and in person at ESIP, Carpentries, Posit, Shannon D, CSCCE Tool Tips, 

We've been able to slow down and catch up a bit over summer, following a busy spring that included the second [NASA Openscapes Champions Cohort](https://openscapes.org/blog/2023-08-01-nasa-champions/), we built a new [Zenodo Openscapes Community](https://openscapes.org/blog/2023-05-31-zenodo-community/) to help find and cite Openscapes things, we [migrated our website to Quarto](TODO LINK TO BLOG), learned [coaching skills that have made us better open data science mentors](https://openscapes.org/blog/2023-05-17-mentor-coach/). 

- Carpentries Instructors training

We also launched two new programs that we will also lead annually: 
- Ileana Fenwick's [Pathway to Open Science](TODO LINK TO BLOG) - join us February 2024!
- [Reflections](TODO LINK TO BLOG) - join us May 2024!




Coming up this fall



Goals this year: stories & connecting to climate and daily 

- 2 publicatinos & submitted
- ESIP in person
- new website
- Launched 2 programs: Pathways and Reflections in Spring. Both upcoming in 2024!! Look for signups
- Champs NASA
