---
title: "The Abundance of Community at the 2024 AGU Meeting"
description: "Reflections following the American Geophysical Union (AGU) Fall Meeting, December 2024."
author: 
  - name: Julie Lowndes
    orcid: 0000-0003-1682-3872
date: 2025-01-20
citation: 
  url: https://openscapes.org/blog/2025-01-20-abundance-of-community-agu
categories: [blog, nasa-framework, noaa-fisheries]
#image: TODO
---

*These are short reflections flying home from the AGU Fall Meeting, where I was buoyed by so many people. As we move into 2025, community is more critical than ever, and spending time on gratitude is a way of keeping grounded and resilient for days ahead. With that idea, I wanted to share some of my notes from December looking forward.*

*Quicklinks:*

-   [*AGU meeting December 2024*] (TODO)
-   Openscapes activities (TODO)
- Google Photo album? subset?
- other?

------------------------------------------------------------------------

## The Serviceberry 

On the plane home I read [The Serviceberry] (TODO) about the gift economy, reciprocity, and gratitude for the abundance of community. This is a new short book by [Dr. Robin Wall Kimmerer] (TODO), and the physical book was a gift of reciprocity given to me by a colleague-friend and fellow resident of Santa Barbara Bruce Caron, in exchange for me bringing EarthArxiv community stickers to AGU.

TODO review notes

One of the themes of Serviceberry is the idea of succession ecology ...TODO


## Acts of Reciprocity at AGU

There were so many acts of reciprocity in the open source/open science community. There were too many to mention fully here but examples that immediately come to mind:

- When I shared goals with Chelle Gentemann, she not only gave recommendations but in-the-moment sent introductions to several people via Slack
- On Monday, Brianna Pagan and I had a long conversation about values, and how they show up in beautiful places where we live that have high fire risk. When Brianna flew home hours later with a wildfire threatening her home, she asked me to give an invited talk for her on Wednesday. I said yes without hesitation, and was so honored that she trusted me to give the talk and was confident in our relationship to ask for help. I know that anyone of the NASA Openscapes Mentors would have said yes too. That is the community of reciprocity and generosity that we have.
- A dear grad school friend saw Openscapes stickers at the NASA booth, which she said was so cool in itself! And she overheard a conversation between graduate students: "Oh you should get an Openscapes sticker, they are a great group!" "Yeah, I already have one!"
- Walking in the cold to see all the Christmas and holiday lights with friends Nikki Tulley and Crista Straub
